#!/bin/python
import sys
import libvirt
import subprocess as sp
import re
from xml.etree.ElementTree import *
import os.path


lstHypervisor = [
    "qemu+ssh://node1/system",
    "qemu+ssh://node2/system",
    "qemu+ssh://node3/system"
]

class ClusterVirt():
    def __init__(self):
        self.lstHV = []
        self.dicFunc = {
            "list":self.ShowGuests,
            "addvm":self.AddVM2PCS,
            "delvm":self.DelVM,
            "migrate":self.migrate,
            "console":self.console,
            "clone":self.clone
            
        }

        for q in lstHypervisor:
            self.lstHV.append(libvirt.open(q))

        # import pprint
        # pprint.pprint(dir(lstHV[0]))


    def ShowGuests(self,argv,argc):
        for hv in self.lstHV:
            print hv.getHostname() + "-"*60
            for id in hv.listDomainsID():
                dom = hv.lookupByID(id)
                infos = dom.info()
                print '  %d\t%s\t%d\t%d\t%d\t%d' % (id,dom.name(),infos[0],infos[1],infos[3],infos[2])

    def AddVM2PCS(self,argv,argc):
        strXMLfile = argv[2]
        if(not os.path.exists(strXMLfile)):
            print "Specified kvm xml file not exist(%s)" % strXMLfile
            return

        p1 = sp.Popen(["grep","<name>",strXMLfile],stdout=sp.PIPE, stderr=sp.PIPE)
        strOut,strErr = p1.communicate()

        if(strErr):
            print "XML file open error(%s)" % strErr
            return
        
        strVMname = re.sub(r' *<\/?name>',"",strOut)
        strVMname = re.sub(r'\n',"",strVMname)

        strPCScmd = 'pcs resource create vm-%s VirtualDomain hypervisor="qemu:///system" config="%s" migration_transport="ssh" meta allow-migrate="true" target-role="Started" op start interval="0" timeout="120s" on-fail="restart" op monitor interval="10s" timeout="30s" on-fail="restart" op stop interval="0" timeout="90s" on-fail="fence" op migrate_to interval="0" timeout="300s" on-fail="fence" op migrate_from interval="0" timeout="240s" on-fail="restart"' % (strVMname,strXMLfile)
        

        # import pprint
        # pprint.pprint(re.split(" ",strPCScmd))
        # return 

        p2 = sp.Popen(re.split(" ",strPCScmd))
        strOut,strErr = p2.communicate()
        if(strErr):
            print "pcs resource add error(%s)" % strErr
            return
        print "add finished"

    def DelVM(self,argv,argc):
        strVMname = argv[2]
        strPCScmd = 'pcs resource delete %s' % strVMname
        p2 = sp.Popen(re.split(" ",strPCScmd))
        strOut,strErr = p2.communicate()
        if(strErr):
            print "pcs resource add error(%s)" % strErr
            return
        print strOut

    def GetVMHost(self,strVMname):
        for hv in self.lstHV:
            for id in hv.listDomainsID():
                dom = hv.lookupByID(id)
                infos = dom.info()
                if(dom.name() == strVMname):
                    return hv,dom
        return None

    def GetHostByName(self,strHostname):
        for hv in self.lstHV:
            if(hv.getHostname() == strHostname):
                return hv
        return None

    def migrate(self,argv,argc):
        if(not argc == 4):
            print "invalid argment: migrate vmname migrateto"
            return
        strVMname = argv[2]
        strNewHost = argv[3]
        strPCScmd = 'pcs resource move %s %s' % (strVMname,strNewHost)
        p2 = sp.Popen(re.split(" ",strPCScmd))
        strOut,strErr = p2.communicate()
        if(strErr):
            print "pcs resource add error(%s)" % strErr
            return
        print strOut
        
    def console(self,argv,argc):
        if(not argc == 3):
            print "invalid argment: console vmname"
            return
        strVMname = argv[2]
        hv,dom = self.GetVMHost(strVMname)
        if(hv == None):
            print "No vm found"
            return
        print "virsh -c qemu+ssh://%s/system console %s" % (hv.getHostname(),strVMname)

    def clone(self,argv,argc):
        if(not argc == 4):
            print "invalid argment: clone xmlfilePath newvmname"
            return

        strXMLFile = argv[2]
        strNewName = argv[3]


        tree = parse(strXMLFile)
        ele = tree.getroot()
        # print ele.find(".//uuid").text
        # print ele.find(".//source").get("name")
        strOrgName = ele.find(".//name").text
        strRBDName = ele.find(".//source").get("name")

        import uuid
        ele.find(".//uuid").text = str(uuid.uuid1())
        ele.find(".//name").text = strNewName
        ele.find(".//source").set("name","rbd/"+strNewName)
        
        for i in  ele.findall(".//interface"):
            i.remove(i.find(".//mac"))
            # import pprint
            # pprint.pprint(dir(ele))

        strPath = re.sub("\/[^\/]*$","",strXMLFile)
        strNEWXML = strPath+"/"+strNewName+".xml"
        if(os.path.exists(strNEWXML)):
            print "Specified kvm xml file already exist(%s)" % strNEWXML
            return

        tree.write(strNEWXML)

            
        """
        rbd snap create rbd/sl71-harmdev@sl71-harmdev-snap
        rbd snap protect rbd/sl71-harmdev@sl71-harmdev-snap
        rbd clone rbd/sl71-harmdev@sl71-harmdev-snap rbd/sl71-harmdev2
        rbd snap unprotect rbd/sl71-harmdev@sl71-harmdev-snap
        """
        from datetime import datetime
        strDate = datetime.now().strftime("%Y%m%d%H%M%S")

        strCmd = "rbd snap create rbd/%s@%s-snap-%s" % (strOrgName,
                                                        strOrgName,
                                                        strDate)
        p2 = sp.Popen(re.split(" ",strCmd))
        strOut,strErr = p2.communicate()
        if(strErr):
            print "rbd snap create error(%s)" % strErr
            return
        print strOut

        strCmd = "rbd snap protect %s@%s-snap-%s" % (strRBDName,
                                                     strOrgName,
                                                     strDate)
        p2 = sp.Popen(re.split(" ",strCmd))
        strOut,strErr = p2.communicate()
        if(strErr):
            print "rbd snap protect error(%s)" % strErr
            return
        print strOut

        strCmd = "rbd clone %s@%s-snap-%s rbd/%s" % (strRBDName,
                                                         strOrgName,
                                                         strDate,
                                                         strNewName)
        p2 = sp.Popen(re.split(" ",strCmd))
        strOut,strErr = p2.communicate()
        if(strErr):
            print "rbd clone error(%s)" % strErr
            return
        print strOut
        
    def DispatchFunc(self):
        argv = sys.argv
        argc = len(argv)
        if(argc == 1):
            argv.append("list")
        # try:
        self.dicFunc[argv[1]](argv,argc)
        # except:
        #     print "err"

if __name__ == "__main__":

    insCV = ClusterVirt()
    insCV.DispatchFunc()
